// Generated by scripts/update-popular-games.mjs. Do not edit by hand.
export const popularGamesSnapshot = {
  "generatedAt": "2026-10-10T08:26:44.997Z",
  "windowDays": 28,
  "source": "MyWebAstra D1 via Cloudflare API",
  "rankings": [
    {
      "href": "/evolve",
      "views": 63
    },
    {
      "href": "/bloodmoney",
      "views": 28
    },
    {
      "href": "/fire-red",
      "views": 26
    },
    {
      "href": "/flappy-text",
      "views": 19
    },
    {
      "href": "/fruit-ninja",
      "views": 8
    },
    {
      "href": "/brush-jjaemu",
      "views": 6
    },
    {
      "href": "/sprunki",
      "views": 5
    },
    {
      "href": "/html5-mario",
      "views": 5
    },
    {
      "href": "/html5demo7",
      "views": 2
    },
    {
      "href": "/html5-fly",
      "views": 2
    },
    {
      "href": "/Spider-Solitaire",
      "views": 1
    },
    {
      "href": "/pac-man",
      "views": 0
    },
    {
      "href": "/html5-xxl",
      "views": 0
    },
    {
      "href": "/mouseHit",
      "views": 0
    },
    {
      "href": "/slot-machine-main",
      "views": 0
    }
  ]
} as const;
