// Generated by scripts/update-popular-games.mjs. Do not edit by hand.
export const popularGamesSnapshot = {
  "generatedAt": "2026-10-08T22:56:54.253Z",
  "windowDays": 28,
  "source": "MyWebAstra D1 via Cloudflare API",
  "rankings": [
    {
      "href": "/evolve",
      "views": 58
    },
    {
      "href": "/bloodmoney",
      "views": 27
    },
    {
      "href": "/fire-red",
      "views": 21
    },
    {
      "href": "/flappy-text",
      "views": 16
    },
    {
      "href": "/fruit-ninja",
      "views": 6
    },
    {
      "href": "/brush-jjaemu",
      "views": 5
    },
    {
      "href": "/sprunki",
      "views": 4
    },
    {
      "href": "/html5-mario",
      "views": 2
    },
    {
      "href": "/html5demo7",
      "views": 2
    },
    {
      "href": "/html5-fly",
      "views": 2
    },
    {
      "href": "/Spider-Solitaire",
      "views": 1
    },
    {
      "href": "/pac-man",
      "views": 0
    },
    {
      "href": "/html5-xxl",
      "views": 0
    },
    {
      "href": "/mouseHit",
      "views": 0
    },
    {
      "href": "/slot-machine-main",
      "views": 0
    }
  ]
} as const;
